name: Build

on:
  push:
  pull_request:
  create:
    tags:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # GitVersioning needs deep clone
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build vsmac-cli.sln --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Publish to GPR
      if: github.event_name == 'push' || github.event_name == 'create'
      run: dotnet nuget push "packages/**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate

    - name: Publish to NuGet.org
      if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
      run: |
          dotnet nuget push "packages/**/*.nupkg" --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
